@startuml architecture

component core{
    package timetable.core
    package timetable.json
}

timetable.core --> timetable.json

component jackson {
    timetable.json --> jackson
}

component fxui {
    package timetable.ui
}

timetable.ui --> timetable.core
timetable.ui --> timetable.json

component javafx { 
    component fxml{

    }
}

fxui --> javafx
fxui --> fxml

component rest {
    package timetable.restapi
    package timetable.restserver
}

timetable.restapi --> timetable.core
timetable.restserver --> timetable.json
timetable.restserver --> timetable.restapi
@enduml
