@startuml
actor User
User -> "ADD EVENT: Button" as addevent: click
addevent -> TimetableController: handleAddEvent
TimetableController -> "~#newTitle: TextField": getText
TimetableController -> "~#newCategory: Choicebox": getValue
TimetableController -> "~#newDate: DatePicker": getValue
TimetableController -> "~#newStartTime: Choicebox": getValue
TimetableController -> "~#newEndTime: Choicebox": getValue
TimetableController -> "~#newDescription: TextField": getText
TimetableController -> "User.TimetableMap": addEvent
User.TimetableMap -> "TimetableController": updateTimetableView


@enduml